//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular_MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> WoodType { get; set; }
        public Nullable<float> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<float> Price { get; set; }
    }
}
