//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular_MVC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Angular_MVC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про компанію.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штапік.
        /// </summary>
        internal static string ProductType_Bead {
            get {
                return ResourceManager.GetString("ProductType_Bead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вагонка.
        /// </summary>
        internal static string ProductType_Lining {
            get {
                return ResourceManager.GetString("ProductType_Lining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налічник.
        /// </summary>
        internal static string ProductType_Platbands {
            get {
                return ResourceManager.GetString("ProductType_Platbands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плінтус.
        /// </summary>
        internal static string ProductType_Plinth {
            get {
                return ResourceManager.GetString("ProductType_Plinth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомий тип.
        /// </summary>
        internal static string Unknown_Type {
            get {
                return ResourceManager.GetString("Unknown_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вільха.
        /// </summary>
        internal static string WoodType_Alder {
            get {
                return ResourceManager.GetString("WoodType_Alder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ясен.
        /// </summary>
        internal static string WoodType_Ash {
            get {
                return ResourceManager.GetString("WoodType_Ash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осика.
        /// </summary>
        internal static string WoodType_Aspen {
            get {
                return ResourceManager.GetString("WoodType_Aspen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липа.
        /// </summary>
        internal static string WoodType_Linden {
            get {
                return ResourceManager.GetString("WoodType_Linden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дуб.
        /// </summary>
        internal static string WoodType_Oak {
            get {
                return ResourceManager.GetString("WoodType_Oak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сосна.
        /// </summary>
        internal static string WoodType_Pine {
            get {
                return ResourceManager.GetString("WoodType_Pine", resourceCulture);
            }
        }
    }
}
